name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
    - name: Output
      run: |
      go run . -s 1990 -e 1999 -o data/launchdata-1990s.json
      go run . -s 2000 -e 2009 -o data/launchdata-2000s.json
      go run . -s 2010 -e 2019 -o data/launchdata-2010s.json
      go run . -s 2020 -e 2022 -o data/launchdata-2020s.json

    - uses: stefanzweifel/git-auto-commit-action@v4

