name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

#    - name: Test
#      run: go test -v ./...
      
    - name: Output
      run: go run . -s 2000 -e 2022 -o output.json
      
    - uses: stefanzweifel/git-auto-commit-action@v4

